### ISSUE TITLE
calendar_import.py sync fails 

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/community#424] opened 2020-10-14 17:38 UTC
I'm attempting to run the calendar_import.py but am getting forbidden errors;
```
ERROR|2020-10-14T09:45:29|calendar_import.py|192| Could not update meeting kf001; Error:
<HttpError 403 when requesting https://www.googleapis.com/calendar/v3/calendars/kubeflow.org_7l5vnbn8suj2se10sen81d9428%40group.calendar.google.com/events/kf001?alt=json returned "Forbidden">
```
I am in the OWNERS file
```
approvers:
  - jtfogarty
```
Do I need to have a G Suite account?

Has anyone run this successfully outside of google? 

@karlschriek
@nicholas-abad
@yuzliu

@jlewi Any guidance on this is greatly appreciated.

**Comment by jlewi** [comment] 2020-10-15 01:24
See:  https://github.com/kubeflow/community/issues/342#issuecomment-708833122

Duplicate of #274

**Closed by jlewi** 2020-10-15 01:24 UTC
Labels: area/community, kind/bug, priority/p0
