### ISSUE TITLE
Archive inactive Kubeflow repos

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/community#479] opened 2021-02-15 23:16 UTC
There are multiple repos in the Kubeflow github organization where no code is being checked in. We shall identify and archive and/or move those repos. I will follow up with a subset of the list, and then we can expand from there.

**Comment by thesuperzapper** [comment] 2021-02-24 02:23
@animeshsingh @Bobgy please list the repos to archive when you are ready

**Comment by animeshsingh** [comment] 2021-02-24 18:18
https://github.com/kubeflow/metadata
https://github.com/kubeflow/fairing
https://github.com/kubeflow/triage-issues
https://github.com/kubeflow/reporting
https://github.com/kubeflow/marketing-materials
https://github.com/kubeflow/batch-predict
https://github.com/kubeflow/example-seldon
https://github.com/kubeflow/homebrew-core

**Comment by Bobgy** [comment] 2021-02-26 23:33
Not sure about fairing, @jinchihe said he wanted to keep maintaining it.

Currently, WGs are paused for expansion of scope. So shall we reconsider that later

**Comment by Bobgy** [comment] 2021-02-26 23:37
https://github.com/kubeflow/kubebench
Is this ready to archive? @kubeflow/wg-training-leads

**Comment by Bobgy** [comment] 2021-02-26 23:40
https://github.com/kubeflow/frontend
KFP should move it's content to KFP repo, then it can be archived

**Comment by Bobgy** [comment] 2021-02-26 23:42
https://github.com/kubeflow/features

**Comment by gaocegege** [comment] 2021-02-27 02:17
> https://github.com/kubeflow/kubebench
> Is this ready to archive? @kubeflow/wg-training-leads

cc @xyhuang

**Comment by gaocegege** [comment] 2021-02-27 02:19
https://github.com/kubeflow/caffe2-operator

**Comment by gaocegege** [comment] 2021-02-27 02:20
https://github.com/kubeflow/chainer-operator

Is it ready to archive?

@everpeace

**Comment by thesuperzapper** [comment] 2021-03-03 13:28
Here is my reading of the final list to be actioned in the next few days.

Please like if you agree, or comment if you disagree.

## To DELETE:
* https://github.com/kubeflow/fastpages
* https://github.com/kubeflow/features
* https://github.com/kubeflow/frontend (move content to `kubeflow/pipelines`)
* https://github.com/kubeflow/homebrew-cask
* https://github.com/kubeflow/homebrew-core
* https://github.com/kubeflow/marketing-materials (move content to `kubeflow/community`)
* https://github.com/kubeflow/triage-issues

## To ARCHIVE:
* https://github.com/kubeflow/batch-predict
* https://github.com/kubeflow/example-seldon
* https://github.com/kubeflow/kubebench
* https://github.com/kubeflow/reporting

## To DISCUSS:

### @kubeflow/wg-training-leads, please confirm if actively maintained:
* https://github.com/kubeflow/caffe2-operator
* https://github.com/kubeflow/chainer-operator
* https://github.com/kubeflow/fate-operator

### @kubeflow/wg-pipeline-leads, please confirm if actively maintained:
* https://github.com/kubeflow/kfp-tekton-backend (seems to be duplicate of the active `kubeflow/kfp-tekton`)
* https://github.com/kubeflow/metadata

### @jinchihe / @xauthulei, please confirm if actively maintained:
* https://github.com/kubeflow/fairing

**Comment by terrytangyuan** [comment] 2021-03-03 13:46
I am not sure about https://github.com/kubeflow/fate-operator. @gaocegege @jiahaoc1993 @LaynePeng Is this project still active?

@thesuperzapper Please archiving instead of deleting. We should never delete a repo.

**Comment by thesuperzapper** [comment] 2021-03-03 13:53
> 
> @thesuperzapper Please archiving instead of deleting. We should never delete a repo.

The the ones I propose to delete are either forks (with no actual commits from us), or effectively empty repos.

**Comment by terrytangyuan** [comment] 2021-03-03 14:01
What about this one? https://github.com/kubeflow/frontend Even though the content will be moved to another repo, there can be lessons learned from history/discussions as well as people's contributions/commits in the past.

**Comment by LaynePeng** [comment] 2021-03-03 14:13
yes, it still active. And it is supporting the latest FATE. Furthermore, we are planning a big refactoring.

Sent from iPhone

在 2021年3月3日，下午9:46，Yuan Tang <notifications@github.com> 写道：

﻿

I am not sure about https://github.com/kubeflow/fate-operator. @gaocegege<https://github.com/gaocegege> @jiahaoc1993<https://github.com/jiahaoc1993> @LaynePeng<https://github.com/LaynePeng> Is this project still active?

@thesuperzapper<https://github.com/thesuperzapper> Please archiving instead of deleting. We should never delete a repo.

**Comment by gaocegege** [comment] 2021-03-03 14:35
https://github.com/kubeflow/fate-operator is active, please keep it.

**Comment by Bobgy** [comment] 2021-03-03 23:33
https://github.com/kubeflow/frontend

Should be archived, there were real work there

**Comment by jinchihe** [comment] 2021-03-04 06:08
personally I suggest keep Fairing, that's used and active. Thanks.

**Comment by Bobgy** [comment] 2021-06-07 10:22
I'm going to act on the following list based on request, please comment ASAP if you disagree with anything:

## To DELETE:
* https://github.com/kubeflow/fastpages
* https://github.com/kubeflow/features
* https://github.com/kubeflow/homebrew-cask
* https://github.com/kubeflow/homebrew-core
* https://github.com/kubeflow/triage-issues

## To ARCHIVE:
* https://github.com/kubeflow/batch-predict
* https://github.com/kubeflow/example-seldon
* https://github.com/kubeflow/reporting
* https://github.com/kubeflow/code-intelligence (based on request: https://github.com/kubeflow/code-intelligence/issues/208)
* https://github.com/kubeflow/caffe2-operator
* https://github.com/kubeflow/metadata

## WAITING:
* https://github.com/kubeflow/frontend (wait for moving content to `kubeflow/pipelines`, then archive)

## To DISCUSS:

### @kubeflow/project-steering-group, please confirm if moving to kubeflow/community?
https://github.com/kubeflow/marketing-materials (move content to `kubeflow/community`)

### @xyhuang, please confirm if we can archive kubebench?
https://github.com/kubeflow/kubebench

### @everpeace, please confirm if actively maintained:
https://github.com/kubeflow/chainer-operator

### @animeshsingh @Tomcli, please confirm if actively maintained:
* https://github.com/kubeflow/kfp-tekton-backend (seems to be duplicate of the active `kubeflow/kfp-tekton`)

**Comment by jbottum** [comment] 2021-06-07 15:46
@Bobgy the fastpages (https://github.com/kubeflow/fastpages) was set-up to help people post to blog.kubeflow.org.   I think we might keep it.

**Comment by terrytangyuan** [comment] 2021-06-07 18:21
> @Bobgy the fastpages (https://github.com/kubeflow/fastpages) was set-up to help people post to blog.kubeflow.org. I think we might keep it.

@jbottum I don't think we need it anymore. The new repo for blog is in https://github.com/kubeflow/blog now.

**Comment by jbottum** [comment] 2021-06-07 18:50
@Bobgy ok, the newer repo looks good.   I agree.

**Comment by zijianjoy** [comment] 2021-11-02 17:51
https://github.com/kubeflow/frontend is ready for archive

**Comment by zijianjoy** [comment] 2021-11-04 21:10
Hello everyone, I am targeting Nov 30th 2021 for archiving the repos mentioned in https://github.com/kubeflow/community/issues/479#issuecomment-855805631, as well as the deletion of repos in the same comment. 

Please let me know if:
1. Any personnel you want to notify about the deletion/archive plan. 
2. Any alternative you suggest people to use after certain repo is archived.
3. Any change you want to make for the deletion/archive plan. 

Thank you so much!

**Comment by terrytangyuan** [comment] 2021-11-06 10:33
@zijianjoy The Training WG has added archival notice and decided to archive operator repos for PyTorch, XGBoost, and MXNet. Could you archive this repos as well? Thanks. See context in https://github.com/kubeflow/training-operator/issues/1423

**Comment by zijianjoy** [comment] 2021-11-08 04:38
Hello @terrytangyuan , sounds good to me for archiving XGBoost, MXNet, PyTorch operators repos.

**Comment by everpeace** [comment] 2021-11-10 12:16
Hi, @Bobgy. sorry for the late response. https://github.com/kubeflow/chainer-operator is not maintained actively anymore. please go archive it.

**Comment by zijianjoy** [comment] 2021-11-10 17:28
Hello @everpeace, would you like to put on deprecation notice on README.md file for chainer-operator using format https://github.com/kubeflow/metadata#warning-kubeflowmetadata-is-not-maintained, and suggest an alternative for this tool? Please let me know once you have added this notice, thank you!

**Comment by js-ts** [comment] 2021-11-14 05:09
Hi, @zijianjoy what about https://github.com/kubeflow/kfctl its not actively maintained, last release was a year ago https://github.com/kubeflow/kfctl/releases/tag/v1.2.0

**Comment by everpeace** [comment] 2021-11-14 09:36
> Please let me know once you have added this notice, thank you!

@zijianjoy I added a deprecation notice on chainer-operator repo.

**Comment by zijianjoy** [comment] 2021-11-15 20:37
@everpeace Thank you! I have added chainer-operator repo to archive list

**Comment by zijianjoy** [comment] 2021-11-16 20:02
Notification has been sent to kubeflow-discuss email list: https://groups.google.com/g/kubeflow-discuss/c/GZw4LsPfrcY

**Comment by terrytangyuan** [comment] 2021-11-16 20:15
Thank you! @zijianjoy

**Comment by zijianjoy** [comment] 2021-12-01 01:39
Hello everyone,

Quick update that I will be taking the action to deprecate inactive repos today. 

Archive:

- https://github.com/kubeflow/batch-predict 
- https://github.com/kubeflow/example-seldon 
- https://github.com/kubeflow/reporting 
- https://github.com/kubeflow/code-intelligence 
- https://github.com/kubeflow/caffe2-operator 
- https://github.com/kubeflow/metadata 
- https://github.com/kubeflow/frontend
- https://github.com/kubeflow/pytorch-operator
- https://github.com/kubeflow/mxnet-operator 
- https://github.com/kubeflow/xgboost-operator 

Delete:

- https://github.com/kubeflow/fastpages 
- https://github.com/kubeflow/features 
- https://github.com/kubeflow/homebrew-cask 
- https://github.com/kubeflow/homebrew-core 
- https://github.com/kubeflow/triage-issues

**Comment by zijianjoy** [comment] 2021-12-01 18:09
Update: The deprecation is finished. Thank you everyone for your help.

**Closed by zijianjoy** 2021-12-01 18:09 UTC

**Comment by Bobgy** [comment] 2021-12-02 03:36
Thank you for driving this!

**Comment by thesuperzapper** [comment] 2021-12-02 04:59
🎉

**Comment by theadactyl** [comment] 2021-12-15 18:51
Thanks James!
