### ISSUE TITLE
Ensure Kubeflow meets the CNCF IP Policy

### ISSUE THREAD

**Issue by annajung** [kubeflow/community#661] opened 2023-11-15 17:27 UTC
Part of https://github.com/cncf/toc/issues/1139

As part of CNCF onboarding, the Kubeflow community must fulfill the [CNCF IP Policy](https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy).

This issue will be used to track progress toward meeting the CNCF IP Policy requirements.

| Status | Owner | Policy | 
| -- | -- | -- |
| In progress ([ref](https://github.com/cncf/toc/issues/1139#issuecomment-1741182164)) | Google + CNCF | (a) Any project that is added to the CNCF must have ownership of its trademark and logo assets transferred to the Linux Foundation. |
| In progress | @jbottum @james-jwu @theadactyl + @rimolive | (b) Each project shall determine whether it will require use of an approved CNCF CLA. For projects that select to use a CLA, all code contributors will undertake the obligations set forth in the Apache contributor license agreement(s), altered only as necessary to identify CNCF as the recipient of the contributions, and which shall be approved by the Governance Board. See CNCF Contributor License Agreements available at https://github.com/cncf/cla. The process for managing contributions in accordance with this policy shall be subject to Governance Board approval. |
| | | (c) All new inbound code contributions to the CNCF shall be (i) accompanied by a Developer Certificate of Origin sign-off (https://developercertificate.org/) and (ii) made under the Apache License, Version 2.0 (available at https://www.apache.org/licenses/LICENSE-2.0), such license to be in addition to, and shall not supersede, obligations undertaken under the contribution license agreement(s) provided for in (b) above. |
| Completed | | (d) All outbound code will be made available under the Apache License, Version 2.0. |
| Completed ([ref](https://github.com/kubeflow/community/issues/661#issuecomment-1828659889)) | | (e) All projects evaluated for inclusion in the CNCF shall be completely licensed under an OSI-approved open source license. If the license for a project included in CNCF is not Apache License, Version 2.0, approval of the Governing Board shall be required. |
| Completed ([ref](https://github.com/kubeflow/website/blob/master/LICENSE)) | | (f) All documentation will be received and made available by the CNCF under the Creative Commons Attribution 4.0 International License. |
| | | (g) If an alternative inbound or outbound license is required for compliance with the license for a leveraged open source project or is otherwise required to achieve the CNCF’s mission, the Governing Board may approve the use of an alternative license for inbound or outbound contributions on an exception basis. |

Interim Steering Committee @james-jwu @theadactyl @jbottum
[Katib](https://github.com/kubeflow/katib/blob/master/OWNERS): @andreyvelich @gaocegege @johnugeorge @tenzen-y
[Manifests](https://github.com/kubeflow/manifests/blob/master/OWNERS): @elikatsis @kimwnasptd @PatrickXYS @StefanoFioravanzo @yanniszark @juliusvonkohout 
[MPI Operator](https://github.com/kubeflow/mpi-operator/blob/master/OWNERS): @alculquicondor @rongou @terrytangyuan
[Notebooks](https://github.com/kubeflow/kubeflow/blob/master/components/OWNERS): @elikatsis @kimwnasptd @thesuperzapper @StefanoFioravanzo @yanniszark
[Pipelines](https://github.com/kubeflow/pipelines/blob/master/OWNERS): @chensun @zijianjoy @james-jwu @IronPan
[Pipelines on Tekton](https://github.com/kubeflow/kfp-tekton/blob/master/OWNERS): @animeshsingh @ckadner @fenglixa @pugangxa @ScrapCodes @Tomcli @yhwang
[Training Operators](https://github.com/kubeflow/training-operator/blob/master/OWNERS): @gaocegege @Jeffwan @johnugeorge @zw0610 @terrytangyuan @tenzen-y @andreyvelich

**Comment by alculquicondor** [comment] 2023-11-27 20:39
I can confirm that mpi-operator is licensed as Apache 2.0

**Comment by Tomcli** [comment] 2023-11-27 21:30
KFP-Tekton is licensed under [Apache 2.0](https://github.com/kubeflow/kfp-tekton/blob/master/LICENSE).

**Comment by annajung** [comment] 2023-11-27 21:39
Sorry folks, looks like simple look up of LICENSE files in each repo would be sufficient for the requirement (e). 
I can confirm that each WG do have LICENSE file and are licensed under Apache 2.0 as listed below

- Katib https://github.com/kubeflow/katib/blob/master/LICENSE
- Manifests https://github.com/kubeflow/manifests
- MPI Operator https://github.com/kubeflow/mpi-operator/blob/master/LICENSE
- Notebooks https://github.com/kubeflow/kubeflow/blob/master/LICENSE
- Pipelines https://github.com/kubeflow/pipelines/blob/master/LICENSE
- Pipelines on Tekton https://github.com/kubeflow/kfp-tekton/blob/master/LICENSE
- Training Operators https://github.com/kubeflow/training-operator/blob/master/LICENSE

No additional action is needed for requirement (e), unless you want to add any comments.

**Comment by annajung** [comment] 2023-12-01 14:54
Hi everyone, I am no longer able to continue on this issue, but @rimolive has volunteered to work on Kubeflow CLA/DCO migration with the interim steering committee to ensure Kubeflow meets the CNCF IP Policy and to update GitHub to ensure DCO or CLA are enabled for all GitHub repositories of the project.

Completion of the tasks should allow this issue to be closed and should be reported back to the main issue https://github.com/cncf/toc/issues/1139 as well. Thanks!

**Comment by jbottum** [comment] 2023-12-07 23:00
@rimolive - James Wu and I discussed in Kubeflow Steering Committee call.  We approved this migration to the CNCF CLA/DCO.   Do we need to enable one or both of these options ?

**Comment by thesuperzapper** [comment] 2023-12-08 03:46
@jbottum The CLA is much more comprehensive than the standard DCO (and we currently don't have a DCO requirement, so it would require contributors to start using the "sign-off" section at the end of their commits if we adopted it).

**Comment by jbottum** [comment] 2023-12-08 22:54
@thesuperzapper I tend to agree with your analysis.   I propose to start with the CNCF CLA option (only).  If some contributors find that unusable and they want/need the DCO, then we can add DCO.    @james-jwu - your thoughts ?

**Comment by rimolive** [comment] 2023-12-11 13:34
@jbottum I added an item in the next Kubeflow Community meeting to discuss the differences.

**Comment by rimolive** [comment] 2023-12-11 17:38
@james-jwu I did that research. 22 out of 24 Graduated CNCF projects are confirmed that they use DCO.

**Comment by rimolive** [comment] 2024-03-08 10:53
Bumping this issue. Since KSC agreed to use DCO and it is implemented the PR checks in Kubeflow repositories, can we consider it done? Or there are still missing action items?

**Comment by terrytangyuan** [comment] 2024-03-08 19:16
DCO/CLA related requirements are met. There's one remaining item from this list though:

>(a) Any project that is added to the CNCF must have ownership of its trademark and logo assets transferred to the Linux Foundation.

Looks like @zijianjoy is working on it based on https://github.com/cncf/toc/issues/1139#issuecomment-1741102035. @zijianjoy Can you confirm that this is done?

**Comment by zijianjoy** [comment] 2024-03-08 19:36
> DCO/CLA related requirements are met. There's one remaining item from this list though:
> 
> > (a) Any project that is added to the CNCF must have ownership of its trademark and logo assets transferred to the Linux Foundation.
> 
> Looks like @zijianjoy is working on it based on [cncf/toc#1139 (comment)](https://github.com/cncf/toc/issues/1139#issuecomment-1741102035). @zijianjoy Can you confirm that this is done?

https://github.com/amye is going to be the best person for sharing the progress on this item.

**Comment by terrytangyuan** [comment] 2024-03-08 19:53
@amye Do you have an update on that? Thanks!

**Comment by amye** [comment] 2024-03-08 19:59
You'll want to do this over in the TOC repo, we have https://github.com/cncf/toc/issues/1139 open for you!

**Comment by zijianjoy** [comment] 2024-03-26 20:35
We have enabled DCO for Kubeflow, as a result, I believe the CNCF IP Policy item is completed. I am going to close this item as finished, feel free to comment if not the case.

**Closed by zijianjoy** 2024-03-26 20:35 UTC
